# Generated by Django 5.0 on 2025-10-14 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Citizen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("citizen_id", models.CharField(db_index=True, max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=500)),
                ("email", models.EmailField(max_length=254)),
                ("operator_id", models.CharField(max_length=100)),
                ("operator_name", models.CharField(max_length=255)),
                ("is_registered", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "citizens",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["citizen_id"], name="citizens_citizen_d5fbeb_idx"),
                    models.Index(fields=["email"], name="citizens_email_765c52_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AffiliationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("VALIDATED", "Citizen Validated"),
                            ("REGISTERED", "Citizen Registered"),
                            ("FAILED", "Registration Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent to Kafka"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("payload", models.JSONField()),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "citizen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="affiliation.citizen",
                    ),
                ),
            ],
            options={
                "db_table": "affiliation_events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "status"], name="affiliation_event_t_36ffc3_idx"
                    ),
                    models.Index(fields=["created_at"], name="affiliation_created_139024_idx"),
                ],
            },
        ),
    ]
