# Generated by Django 5.0 on 2025-10-15 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Affiliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "operator_id",
                    models.CharField(
                        help_text="ID of the operator this citizen is affiliated with",
                        max_length=100,
                    ),
                ),
                (
                    "operator_name",
                    models.CharField(
                        help_text="Name of the operator this citizen is affiliated with",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AFFILIATED", "Affiliated"),
                            ("TRANSFERRING", "Transferring"),
                            ("TRANSFERRED", "Transferred"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="AFFILIATED",
                        help_text="Current affiliation status",
                        max_length=20,
                    ),
                ),
                (
                    "affiliated_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the citizen was first affiliated"
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last time the status was changed"
                    ),
                ),
                (
                    "transfer_destination_operator_id",
                    models.CharField(
                        blank=True,
                        help_text="Operator ID where citizen is being/was transferred to",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "transfer_destination_operator_name",
                    models.CharField(
                        blank=True,
                        help_text="Operator name where citizen is being/was transferred to",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the affiliation", null=True
                    ),
                ),
                (
                    "citizen",
                    models.OneToOneField(
                        help_text="The citizen affiliated with the operator",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affiliation",
                        to="affiliation.citizen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Affiliation",
                "verbose_name_plural": "Affiliations",
                "db_table": "affiliations",
                "ordering": ["-affiliated_at"],
            },
        ),
        migrations.DeleteModel(
            name="AffiliationEvent",
        ),
        migrations.AddIndex(
            model_name="affiliation",
            index=models.Index(
                fields=["status", "affiliated_at"], name="affiliation_status_d2682d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="affiliation",
            index=models.Index(fields=["operator_id"], name="affiliation_operato_16b611_idx"),
        ),
    ]
