# Generated by Django 5.0 on 2025-10-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliation", "0002_affiliation_delete_affiliationevent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="citizen",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether the citizen is currently active"
            ),
        ),
    ]
