# Generated by Django 5.0 on 2025-10-15 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("affiliation", "0003_citizen_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="citizen",
            name="is_active",
        ),
    ]
