# Generated by Django 5.0 on 2025-10-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliation", "0004_remove_citizen_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="affiliation",
            name="documents_ready",
            field=models.BooleanField(
                default=False,
                help_text="Whether documents have been downloaded and uploaded by document service",
            ),
        ),
        migrations.AddField(
            model_name="affiliation",
            name="transfer_completed_at",
            field=models.DateTimeField(
                blank=True, help_text="When the transfer was completed", null=True
            ),
        ),
        migrations.AddField(
            model_name="affiliation",
            name="transfer_confirmation_url",
            field=models.URLField(
                blank=True,
                help_text="URL to call for transfer confirmation",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="affiliation",
            name="transfer_source_operator_id",
            field=models.CharField(
                blank=True,
                help_text="Operator ID where citizen is being transferred from (for incoming transfers)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="affiliation",
            name="transfer_source_operator_name",
            field=models.CharField(
                blank=True,
                help_text="Operator name where citizen is being transferred from",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="affiliation",
            name="transfer_started_at",
            field=models.DateTimeField(
                blank=True, help_text="When the transfer process started", null=True
            ),
        ),
    ]
