# Generated by Django 5.0 on 2025-10-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliation", "0005_affiliation_documents_ready_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="citizen",
            name="is_verified",
            field=models.BooleanField(
                default=False, help_text="Whether registration is confirmed by MINTIC"
            ),
        ),
        migrations.AddField(
            model_name="citizen",
            name="pending_deletion",
            field=models.BooleanField(
                default=False, help_text="Whether citizen is pending deletion after unregister"
            ),
        ),
        migrations.AddField(
            model_name="citizen",
            name="verification_message",
            field=models.TextField(
                blank=True, help_text="Message from MINTIC verification", null=True
            ),
        ),
        migrations.AddField(
            model_name="citizen",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending MINTIC Verification"),
                    ("verified", "Verified by MINTIC"),
                    ("failed", "Verification Failed"),
                ],
                default="pending",
                help_text="Current verification status",
                max_length=50,
            ),
        ),
    ]
