# Generated by Django 5.0 on 2025-10-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0006_citizen_is_verified_citizen_pending_deletion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliation',
            name='transfer_destination_api_url',
            field=models.URLField(blank=True, help_text='API URL of the target operator for transfer', max_length=500, null=True),
        ),
    ]
