apiVersion: v1
kind: PersistentVolume
metadata:
  name: citizen-affiliation-pv
  namespace: citizen-affiliation
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data/citizen-affiliation
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: citizen-affiliation-pvc
  namespace: citizen-affiliation
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
